---
title: "EconomistVisualizations"
author: "André Calero Valdez"
date: "16 4 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggthemes)
```


```{r}
brexit <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-16/brexit.csv")
names(brexit)

my_blue <- "#2c7bb6"
my_red <- "#d7191c"


df <- brexit %>% 
  mutate(date = dmy(date), 
         #percent_undecided = (100 - percent_responding_right - percent_responding_wrong)/100,
         percent_responding_right = percent_responding_right / 100,
         percent_responding_wrong = percent_responding_wrong / 100
         ) %>% 
  gather(vote, value, -date)
df %>% 
  ggplot() + 
  aes(x = date, y=value, color = vote)  +  
  geom_point(size = 2, alpha = 0.3) +
  geom_smooth(se = FALSE) +
  scale_y_continuous(name = "Zustimmung in Prozent", labels = scales::percent_format(accuracy = 1)) +
  scale_x_date(name = "", date_labels = "%B %Y") +
  scale_color_manual(values = c(my_blue, my_red)) +
  labs(title="Zustimmung mit dem Brexit nimmt leicht ab", 
       subtitle = "Brexit Abstimmung war am 23. Juni 2016",
       caption = "Source: NatCen Social Research") +
  # Annotationen
  # geom_vline(xintercept = dmy("23/6/2016"), color = "red") +
  theme_economist_white() +
  guides(color = FALSE) +
  annotate("text", label = "Ablehner", x = dmy("1/3/2018"), y = 0.464, size = 6, color = my_red) +
  geom_curve(aes(x = dmy("1/3/2018"), y =  0.46, xend = dmy("20/3/2018"), yend = 0.455), curvature = 0.1, 
                  arrow = arrow(length = unit(0.15, "cm"))) +
  annotate("text", label = "Zustimmer", x = dmy("1/3/2018"), y = 0.416, size = 6, color = my_blue) +
  geom_curve(aes(x = dmy("1/3/2018"), y =  0.42, xend = dmy("20/3/2018"), yend = 0.424), curvature = 0.1, 
                  arrow = arrow(length = unit(0.15, "cm")), color = my_blue) +
  NULL


```

